INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400000, '2022-01-02',  "Buffering");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400001, '2022-01-03',  "Not able to access the subtitles");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400002, '2022-01-04',  "Buffering");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400003, '2022-01-05',  "Problems with the subtitles or captions, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400004, '2022-01-06',  "Problems with the audio or dubbing, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400005, '2022-01-07',  "Problems with the video quality or aspect ratio");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400006, '2022-01-08',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400007, '2022-01-09',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400008, '2022-01-10',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400009, '2022-01-11',  "Artwork or description errors");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400010, '2022-01-12',  "Problems with the video quality or aspect ratio");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400011, '2022-01-13',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400012, '2022-01-14',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400013, '2022-01-15',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400014, '2022-01-16',  "Problems with the subtitles or captions, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400015, '2022-01-17',  "Problems with the audio or dubbing, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400016, '2022-01-18',  "Problems with the video quality or aspect ratio");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400017, '2022-01-19',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400018, '2022-01-20',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400019, '2022-01-21',  "Problems with the subtitles or captions, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400020, '2022-01-22',  "Problems with the audio or dubbing, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400021, '2022-01-23',  "Problems with the video quality or aspect ratio");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400022, '2022-01-24',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400023, '2022-01-25',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400024, '2022-01-26',  "Problems with the subtitles or captions, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400025, '2022-01-27',  "Problems with the audio or dubbing, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400026, '2022-01-28',  "Problems with the video quality or aspect ratio");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400027, '2022-01-29',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400028, '2022-01-30',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400029, '2022-01-31',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400030, '2022-02-01',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400031, '2022-02-02',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400032, '2022-02-03',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400033, '2022-02-04',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400034, '2022-02-05',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400035, '2022-02-06',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400046, '2022-02-07',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400047, '2022-02-08',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400048, '2022-02-09',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400049, '2022-02-10',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400050, '2022-02-11',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400051, '2022-02-12',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400052, '2022-02-13',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400053, '2022-02-14',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400044, '2022-02-15',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400045, '2022-02-16',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400048, '2022-02-17',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400049, '2022-02-18',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400050, '2022-02-19',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400051, '2022-02-20',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400035, '2022-02-21',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400046, '2022-02-22',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400047, '2022-02-23',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400048, '2022-02-24',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400049, '2022-02-25',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400055, '2022-02-26',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400056, '2022-02-27',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400057, '2022-02-28',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400058, '2022-03-01',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400059, '2022-03-02',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400060, '2022-03-03',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400061, '2022-03-04',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400062, '2022-03-05',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400063, '2022-02-11',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400064, '2022-02-12',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400065, '2022-02-13',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400066, '2022-02-14',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400067, '2022-02-15',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400068, '2022-02-16',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400069, '2022-02-17',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400070, '2022-02-18',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400071, '2022-02-19',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400072, '2022-02-11',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400073, '2022-02-12',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400074, '2022-02-13',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400075, '2022-02-14',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400076, '2022-02-15',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400077, '2022-02-16',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400078, '2022-02-17',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400079, '2022-02-18',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400080, '2022-02-19',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400001, '2022-02-20',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400002, '2022-02-21',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400003, '2022-02-22',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400004, '2022-02-23',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400005, '2022-02-17',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400006, '2022-02-18',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400007, '2022-02-19',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400008, '2022-02-20',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400009, '2022-02-21',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400010, '2022-02-22',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400011, '2022-02-23',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400012, '2022-02-22',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400013, '2022-02-23',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400014, '2022-02-17',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400015, '2022-02-18',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400016, '2022-02-19',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400017, '2022-02-20',  "Problems with the maturity rating or classification");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400018, '2022-02-21',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400019, '2022-02-22',  "Buffering");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400020, '2022-02-23',  "Problems with the subtitles or captions, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400021, '2022-01-02',  "Problems with the audio or dubbing, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400022, '2022-01-03',  "Problems with the video quality or aspect ratio");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400023, '2022-01-04',  "Volume levels");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400104, '2022-01-05',  "Episodes or seasons out of order");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400105, '2022-01-06',  "Problems with the subtitles or captions, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400106, '2022-01-07',  "Problems with the audio or dubbing, including quality or availability");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400107, '2022-01-08',  "Problems with the video quality or aspect ratio");
INSERT INTO service_request_info(service_id,date_of_complaint,complaint_description) VALUES (400108, '2022-01-09',  "Problems with the audio or dubbing, including quality or availability");
